### PR TITLE
Add git and docker setup for Ubuntu

### PR DESCRIPTION
**Pull request by gibfahn**
Currently only helm and kube get installed, it would be great to give people docker and git as well.

#### Possibly contentious:

- Added the steps to run Docker as a non-root user
- Used the git maintainers ppa rather than the built-in one (because that way you actually get the latest version of git)

### CODE REVIEW

**Comment by kfbishop** [comment]
Requires manual merge due to other changes, but mostly looks good.  
Need to be lenient for non-ubuntu linux system

**Comment by gibfahn** [comment]
>Requires manual merge due to other changes, but mostly looks good.

I'm happy to rebase if necessary, but I'm not seeing anything new on `master`.

image

>Need to be lenient for non-ubuntu linux system

This should do what it did before, namely `warn_unsupported` (which fails with an `error`). I agree that it probably makes more sense to have an `error_unsupported`, and only call that if you actually want to bail out (although I'm not sure when you would want to bail out).

**Comment by gibfahn** [comment]
Okay, I see some changes have landed. Rebased.

**Comment by kfbishop** [comment]
Merged

**Comment by kfbishop** [comment]
@gibfahn Thanks for this update!  I tested on a clean install of ubuntu and it worked flawlessly. cheers.

**Pull request merged**
